### ISSUE TITLE
doesn't work on ubuntu 24.04

### ISSUE THREAD

**Issue by naebushi** [igroman787/mytonctrl#473]
after fresh installation (no errors during install):

```
MyTonCtrl> status
[debug]   21.07.2025, 15:52:30.309 (UTC)  <MainThread>  start GetValidatorWallet function
[debug]   21.07.2025, 15:52:30.309 (UTC)  <MainThread>  start GetLocalWallet function
[debug]   21.07.2025, 15:52:30.309 (UTC)  <MainThread>  start GetWalletFromFile function
[debug]   21.07.2025, 15:52:30.311 (UTC)  <MainThread>  start WalletVersion2Wallet function
[debug]   21.07.2025, 15:52:30.311 (UTC)  <MainThread>  start GetDbSize function
Error: 'list' object has no attribute 'items'

```
